### ISSUE TITLE
Run dbupdater without ssl cert

### ISSUE THREAD

**Issue by CaioIcy** [PET-UnB/pet#3]
On branch [no-cert-flag](https://github.com/PET-UnB/pet/tree/no-cert-flag).

We need a way to run pet-update without creating the ssl certificate

**Comment by CaioIcy** [comment]
@danielhmarinho

**Comment by danielhmarinho** [comment]
Changing milestone due to issue not being finished in time.

**Comment by danielhmarinho** [comment]
Tests need to be implemented
@victorcabeceira 
@aldarionsevero
