### ISSUE TITLE
Flake8

### ISSUE THREAD

**Issue by victorcabeceira** [PET-UnB/pet#4]
Applying flake8 on pet files. Code available in [flake8](https://github.com/PET-UnB/pet/tree/flake8) branch.

**Comment by victorcabeceira** [comment]
@TiagoAssuncao is also working on this issue.

**Comment by TiagoAssuncao** [comment]
@lucaskanashiro @lucasmoura the bug was fixed

**Comment by lucasmoura** [comment]
Running with this configuration: 
2.5.4 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 2.7.11+ on Linux

The following warnings can still be found on the code:

./pet/classifier.py:47:9: F841 local variable 'highest_tag' is assigned to but never used
./pet/vcs.py:136:9: F841 local variable 'root' is assigned to but never used
./pet/web/views.py:23:1: F401 'HTTPBadRequest' imported but unused
./pet/web/views.py:27:1: F401 're' imported but unused
./pet/web/views.py:46:68: E711 comparison to None should be 'if cond is None:'
./pet/web/views.py:77:5: F841 local variable 'repo_name' is assigned to but never used
